import type { AddressRow } from '../../../types/network'
import type { NetworkLayer, Site } from '../../../types/slide'

export const LAYER_CLASS: Record<NetworkLayer, string> = {
  Core: 'tc-core',
  'Core WAN': 'tc-core',
  Distribuição: 'tc-dist',
  Acesso: 'tc-acc',
  Endpoint: 'tc-end',
  Reserva: 'tc-res',
}

export const SITE_LABEL: Record<Site, string> = {
  'Matriz SP': 'Matriz SP',
  'Filial CWB': 'Filial CWB',
  'VPN Tunnel': 'VPN Tunnel',
  'VPN SSL': 'VPN SSL',
}

export const ADDRESSES: AddressRow[] = [
  {
    site: 'Matriz SP',
    device: 'Gateway WAN MPLS (Operadora A)',
    ip: '203.0.113.1',
    mask: '/30',
    gateway: '203.0.113.2',
    layer: 'Core WAN',
  },
  {
    site: 'Matriz SP',
    device: 'Gateway WAN Internet (Operadora B)',
    ip: '198.51.100.1',
    mask: '/30',
    gateway: '198.51.100.2',
    layer: 'Core WAN',
  },
  {
    site: 'Matriz SP',
    device: 'Firewall FortiGate 600F (HA)',
    ip: 'Perimetro da Matriz',
    mask: 'N/A',
    gateway: '—',
    layer: 'Core',
  },
  {
    site: 'Matriz SP',
    device: 'Core Catalyst 9500 (Gerencia)',
    ip: '10.10.99.2',
    mask: '/27',
    gateway: '10.10.99.1',
    layer: 'Distribuição',
  },
  {
    site: 'Matriz SP',
    device: 'VLAN 10 - Servidores Producao',
    ip: '10.10.10.0',
    mask: '/24',
    gateway: '10.10.10.1',
    layer: 'Acesso',
  },
  {
    site: 'Matriz SP',
    device: 'VLAN 20 - Servidores Dev/Homolog',
    ip: '10.10.20.0',
    mask: '/24',
    gateway: '10.10.20.1',
    layer: 'Acesso',
  },
  {
    site: 'Matriz SP',
    device: 'VLAN 30 - TI / Infraestrutura',
    ip: '10.10.30.0',
    mask: '/24',
    gateway: '10.10.30.1',
    layer: 'Endpoint',
  },
  {
    site: 'Matriz SP',
    device: 'VLAN 40 - Desenvolvimento',
    ip: '10.10.40.0',
    mask: '/23',
    gateway: '10.10.40.1',
    layer: 'Endpoint',
  },
  {
    site: 'Matriz SP',
    device: 'VLAN 50 - Administrativo',
    ip: '10.10.50.0',
    mask: '/23',
    gateway: '10.10.50.1',
    layer: 'Endpoint',
  },
  {
    site: 'Matriz SP',
    device: 'VLAN 60 - Comercial / Suporte',
    ip: '10.10.60.0',
    mask: '/23',
    gateway: '10.10.60.1',
    layer: 'Endpoint',
  },
  {
    site: 'Matriz SP',
    device: 'VLAN 70 - Wi-Fi Corporativo',
    ip: '10.10.70.0',
    mask: '/24',
    gateway: '10.10.70.1',
    layer: 'Endpoint',
  },
  {
    site: 'Matriz SP',
    device: 'VLAN 80 - Wi-Fi Visitantes',
    ip: '10.10.80.0',
    mask: '/24',
    gateway: '10.10.80.1',
    layer: 'Endpoint',
  },
  {
    site: 'Matriz SP',
    device: 'VLAN 99 - Gerencia de Rede',
    ip: '10.10.99.0',
    mask: '/27',
    gateway: '10.10.99.1',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'Gateway WAN MPLS (Operadora A)',
    ip: '203.0.113.5',
    mask: '/30',
    gateway: '203.0.113.6',
    layer: 'Core WAN',
  },
  {
    site: 'Filial CWB',
    device: 'Gateway WAN Internet + VPN (Operadora B)',
    ip: '198.51.100.5',
    mask: '/30',
    gateway: '198.51.100.6',
    layer: 'Core WAN',
  },
  {
    site: 'Filial CWB',
    device: 'Firewall de borda da Filial',
    ip: 'Perimetro da Filial',
    mask: 'N/A',
    gateway: '—',
    layer: 'Core',
  },
  {
    site: 'Filial CWB',
    device: 'Desenvolvimento (dimensionado)',
    ip: 'Sub-rede para 144 hosts',
    mask: '/24',
    gateway: 'SVI Desenvolvimento',
    layer: 'Distribuição',
  },
  {
    site: 'Filial CWB',
    device: 'Suporte (dimensionado)',
    ip: 'Sub-rede para 108 hosts',
    mask: '/25',
    gateway: 'SVI Suporte',
    layer: 'Acesso',
  },
  {
    site: 'Filial CWB',
    device: 'Administrativo (dimensionado)',
    ip: 'Sub-rede para 72 hosts',
    mask: '/25',
    gateway: 'SVI Administrativo',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'TI / Infraestrutura (dimensionado)',
    ip: 'Sub-rede para 36 hosts',
    mask: '/26',
    gateway: 'SVI TI/Infra',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'VLAN Servidores locais',
    ip: 'Sub-rede para 6-8 servidores',
    mask: '/28',
    gateway: 'SVI Servidores',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'VLAN de Gerencia',
    ip: 'Rede de switches, APs e ativos',
    mask: '/27',
    gateway: 'SVI Gerencia',
    layer: 'Acesso',
  },
  {
    site: 'Filial CWB',
    device: 'Wi-Fi Corporativo',
    ip: 'Segmento dedicado para funcionarios',
    mask: 'Definido no projeto logico',
    gateway: 'SVI Wi-Fi Corp',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'Wi-Fi Visitantes',
    ip: 'Segmento isolado da rede interna',
    mask: 'Definido no projeto logico',
    gateway: 'SVI Visitantes',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'Reserva operacional planejada',
    ip: 'Capacidade total para 360 usuarios',
    mask: 'Crescimento 3 anos + 20%',
    gateway: 'Aplicavel por VLAN',
    layer: 'Reserva',
  },
  {
    site: 'VPN Tunnel',
    device: 'Contingencia IPsec IKEv2',
    ip: '198.51.100.5 ↔ 198.51.100.1',
    mask: 'IPv4 over Internet',
    gateway: 'Metrica 20 (backup)',
    layer: 'Core WAN',
  },
  {
    site: 'VPN SSL',
    device: 'Pool Clientes Remotos',
    ip: '10.10.1.0',
    mask: '/28',
    gateway: '—',
    layer: 'Core WAN',
  },
]