import type { AddressRow } from '../../../types/network'
import type { NetworkLayer, Site } from '../../../types/slide'

export const LAYER_CLASS: Record<NetworkLayer, string> = {
  Core: 'tc-core',
  'Core WAN': 'tc-core',
  Distribuição: 'tc-dist',
  Acesso: 'tc-acc',
  Endpoint: 'tc-end',
  Reserva: 'tc-res',
}

export const SITE_LABEL: Record<Site, string> = {
  'Matriz SP': 'Matriz SP',
  'Filial CWB': 'Filial CWB',
  'VPN Tunnel': 'VPN Tunnel',
  'VPN SSL': 'VPN SSL',
}

export const ADDRESSES: AddressRow[] = [
  {
    site: 'Matriz SP',
    device: 'Roteador (LAN)',
    ip: '10.0.1.1',
    mask: '/24',
    gateway: 'ISP 200.10.1.2',
    layer: 'Core',
  },
  {
    site: 'Matriz SP',
    device: 'Roteador (WAN)',
    ip: '200.10.1.1',
    mask: '/30',
    gateway: '200.10.1.2',
    layer: 'Core',
  },
  {
    site: 'Matriz SP',
    device: 'Firewall',
    ip: '10.0.1.1',
    mask: '/24',
    gateway: '—',
    layer: 'Core',
  },
  {
    site: 'Matriz SP',
    device: 'Switch L3',
    ip: '10.0.1.2',
    mask: '/24',
    gateway: '10.0.1.1',
    layer: 'Distribuição',
  },
  {
    site: 'Matriz SP',
    device: 'Servidores (3)',
    ip: '10.0.1.200–.202',
    mask: '/24',
    gateway: '10.0.1.1',
    layer: 'Acesso',
  },
  {
    site: 'Matriz SP',
    device: 'PCs Admin (21)',
    ip: '10.0.1.10–.30',
    mask: '/24',
    gateway: '10.0.1.1',
    layer: 'Endpoint',
  },
  {
    site: 'Matriz SP',
    device: 'Impressoras (3)',
    ip: '10.0.1.40–.42',
    mask: '/24',
    gateway: '10.0.1.1',
    layer: 'Endpoint',
  },
  {
    site: 'Matriz SP',
    device: 'VoIP (6)',
    ip: '10.0.1.50–.55',
    mask: '/24',
    gateway: '10.0.1.1',
    layer: 'Endpoint',
  },
  {
    site: 'Matriz SP',
    device: 'PCs VPN Remoto (2)',
    ip: '10.0.1.100–.101',
    mask: '/24',
    gateway: '10.0.1.1',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'Roteador (LAN)',
    ip: '10.0.2.1',
    mask: '/25',
    gateway: 'ISP 200.20.1.2',
    layer: 'Core',
  },
  {
    site: 'Filial CWB',
    device: 'Roteador (WAN)',
    ip: '200.20.1.1',
    mask: '/30',
    gateway: '200.20.1.2',
    layer: 'Core',
  },
  {
    site: 'Filial CWB',
    device: 'Firewall',
    ip: '10.0.2.1',
    mask: '/25',
    gateway: '—',
    layer: 'Core',
  },
  {
    site: 'Filial CWB',
    device: 'Switch L3',
    ip: '10.0.2.2',
    mask: '/25',
    gateway: '10.0.2.1',
    layer: 'Distribuição',
  },
  {
    site: 'Filial CWB',
    device: 'Servidores (2)',
    ip: '10.0.2.200–.201',
    mask: '/25',
    gateway: '10.0.2.1',
    layer: 'Acesso',
  },
  {
    site: 'Filial CWB',
    device: 'Computadores (22)',
    ip: '10.0.2.10–.31',
    mask: '/25',
    gateway: '10.0.2.1',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'Impressoras (4)',
    ip: '10.0.2.40–.43',
    mask: '/25',
    gateway: '10.0.2.1',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'VoIP (8)',
    ip: '10.0.2.50–.57',
    mask: '/25',
    gateway: '10.0.2.1',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'Access Points (4)',
    ip: '10.0.2.60–.63',
    mask: '/25',
    gateway: '10.0.2.1',
    layer: 'Acesso',
  },
  {
    site: 'Filial CWB',
    device: 'Dispositivos Wi-Fi',
    ip: '10.0.2.70–.85',
    mask: '/25',
    gateway: '10.0.2.1',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'PCs VPN Remoto (2)',
    ip: '10.0.2.100–.101',
    mask: '/25',
    gateway: '10.0.2.1',
    layer: 'Endpoint',
  },
  {
    site: 'Filial CWB',
    device: 'Reserva Crescimento',
    ip: '10.0.2.110–.126',
    mask: '/25',
    gateway: '10.0.2.1',
    layer: 'Reserva',
  },
  {
    site: 'VPN Tunnel',
    device: 'Tunel Site-to-Site',
    ip: '10.10.0.0',
    mask: '/30',
    gateway: '—',
    layer: 'Core WAN',
  },
  {
    site: 'VPN SSL',
    device: 'Pool Clientes Remotos',
    ip: '10.10.1.0',
    mask: '/28',
    gateway: '—',
    layer: 'Core WAN',
  },
]