import type { NodeCategory } from '../types';

export const SCHEMA_VERSION = 3;

export const CATEGORY_CODE_MAP: Record<NodeCategory, string> = {
  wan: 'WAN',
  router: 'RTR',
  firewall: 'FW',
  switch: 'SW',
  'load-balancer': 'LB',
  'access-point': 'AP',
  ids: 'IDS',
  ips: 'IPS',
  proxy: 'PX',
  modem: 'MDM',
  dns: 'DNS',
  dhcp: 'DHCP',
  nas: 'NAS',
  printer: 'PRN',
  voip: 'VOIP',
  pc: 'PC',
  server: 'SRV',
  sdwan: 'SDW',
  vpn: 'VPN',
  ipsec: 'IPSEC',
  wireguard: 'WG',
  mpls: 'MPLS',
  gre: 'GRE',
};

export const CATEGORY_HOST_BASE_MAP: Record<NodeCategory, number> = {
  wan: 1,
  router: 10,
  firewall: 20,
  switch: 30,
  'load-balancer': 40,
  'access-point': 50,
  ids: 60,
  ips: 70,
  proxy: 80,
  modem: 90,
  dns: 100,
  dhcp: 110,
  nas: 120,
  printer: 130,
  voip: 140,
  pc: 150,
  server: 160,
  sdwan: 170,
  vpn: 180,
  ipsec: 190,
  wireguard: 200,
  mpls: 210,
  gre: 220,
};
