import type {
  TechFieldSchema,
  TechKind,
  TechProfileContext,
  TechValue,
} from '../types';

export const TECH_PROFILE_VERSION = 1;

export const TECH_SCHEMA: Record<TechKind, TechFieldSchema[]> = {
  router: [
    {
      key: 'gatewayDefault',
      label: 'Gateway Padrao',
      labels: {
        pt: 'Gateway Padrão',
        en: 'Default Gateway',
        es: 'Gateway Predeterminado',
      },
      type: 'boolean',
    },
    {
      key: 'routingMode',
      label: 'Roteamento',
      labels: { pt: 'Roteamento', en: 'Routing', es: 'Enrutamiento' },
      type: 'select',
      options: ['static', 'ospf', 'bgp', 'mixed'],
    },
    {
      key: 'natMode',
      label: 'NAT',
      labels: { pt: 'NAT', en: 'NAT', es: 'NAT' },
      type: 'select',
      options: ['none', 'snat', 'dnat', 'pat', 'hybrid'],
    },
    {
      key: 'stateMode',
      label: 'Estado',
      labels: { pt: 'Estado', en: 'State', es: 'Estado' },
      type: 'select',
      options: ['stateful', 'stateless', 'n-a'],
    },
    {
      key: 'wanUplink',
      label: 'Uplink WAN',
      labels: { pt: 'Uplink WAN', en: 'WAN Uplink', es: 'Enlace WAN' },
      type: 'text',
    },
    {
      key: 'qosEnabled',
      label: 'QoS',
      labels: { pt: 'QoS Habilitado', en: 'QoS Enabled', es: 'QoS Habilitado' },
      type: 'boolean',
    },
    {
      key: 'dscpMarking',
      label: 'DSCP Marking',
      labels: { pt: 'DSCP Marking', en: 'DSCP Marking', es: 'Marcado DSCP' },
      type: 'boolean',
      visibleWhen: { qosEnabled: true },
    },
  ],
  firewall: [
    {
      key: 'gatewayDefault',
      label: 'Gateway Padrao',
      labels: {
        pt: 'Gateway Padrão',
        en: 'Default Gateway',
        es: 'Gateway Predeterminado',
      },
      type: 'boolean',
    },
    {
      key: 'natMode',
      label: 'NAT',
      labels: { pt: 'NAT', en: 'NAT', es: 'NAT' },
      type: 'select',
      options: ['none', 'snat', 'dnat', 'pat', 'hybrid'],
    },
    {
      key: 'stateMode',
      label: 'Modo de Inspecao',
      labels: {
        pt: 'Modo de Inspeção',
        en: 'Inspection Mode',
        es: 'Modo de Inspección',
      },
      type: 'select',
      options: ['stateful', 'stateless'],
    },
    {
      key: 'defaultPolicy',
      label: 'Politica Padrao',
      labels: {
        pt: 'Política Padrão',
        en: 'Default Policy',
        es: 'Política Predeterminada',
      },
      type: 'select',
      options: ['deny', 'allow'],
    },
    {
      key: 'idsIpsIntegration',
      label: 'Integracao IDS/IPS',
      labels: {
        pt: 'Integração IDS/IPS',
        en: 'IDS/IPS Integration',
        es: 'Integración IDS/IPS',
      },
      type: 'select',
      options: ['none', 'ids', 'ips', 'both'],
    },
    {
      key: 'sessionTimeout',
      label: 'Session Timeout (s)',
      labels: {
        pt: 'Timeout de Sessão (s)',
        en: 'Session Timeout (s)',
        es: 'Timeout de Sesión (s)',
      },
      type: 'number',
      min: 30,
      max: 86400,
    },
    {
      key: 'maxConnections',
      label: 'Máx. Conexões',
      labels: {
        pt: 'Máx. Conexões',
        en: 'Max Connections',
        es: 'Máx. Conexiones',
      },
      type: 'number',
      min: 100,
      max: 10000000,
    },
  ],
  vpn: [
    {
      key: 'tunnelType',
      label: 'Tipo de Tunel',
      labels: { pt: 'Tipo de Túnel', en: 'Tunnel Type', es: 'Tipo de Túnel' },
      type: 'select',
      options: [
        'ipsec-site-to-site',
        'ssl-remote',
        'wireguard',
        'sdwan',
        'mpls',
        'gre',
      ],
    },
    {
      key: 'encryptionSuite',
      label: 'Criptografia',
      labels: { pt: 'Criptografia', en: 'Encryption', es: 'Cifrado' },
      type: 'text',
    },
    {
      key: 'authMethod',
      label: 'Autenticacao',
      labels: { pt: 'Autenticação', en: 'Authentication', es: 'Autenticación' },
      type: 'select',
      options: ['psk', 'certificate', 'eap', 'keypair', 'none'],
    },
    {
      key: 'ikeVersion',
      label: 'IKE',
      labels: { pt: 'IKE', en: 'IKE', es: 'IKE' },
      type: 'select',
      options: ['ikev1', 'ikev2', 'n-a'],
    },
    {
      key: 'remotePeer',
      label: 'Peer Remoto',
      labels: { pt: 'Peer Remoto', en: 'Remote Peer', es: 'Par Remoto' },
      type: 'text',
    },
    {
      key: 'dpdKeepalive',
      label: 'DPD/Keepalive',
      labels: { pt: 'DPD/Keepalive', en: 'DPD/Keepalive', es: 'DPD/Keepalive' },
      type: 'boolean',
    },
    {
      key: 'dpdInterval',
      label: 'DPD Intervalo (s)',
      labels: {
        pt: 'DPD Intervalo (s)',
        en: 'DPD Interval (s)',
        es: 'Intervalo DPD (s)',
      },
      type: 'number',
      min: 1,
      max: 300,
      visibleWhen: { dpdKeepalive: true },
    },
    {
      key: 'dpdRetries',
      label: 'DPD Tentativas',
      labels: { pt: 'DPD Tentativas', en: 'DPD Retries', es: 'Reintentos DPD' },
      type: 'number',
      min: 1,
      max: 10,
      visibleWhen: { dpdKeepalive: true },
    },
    {
      key: 'ikeLifetime',
      label: 'IKE Lifetime (s)',
      labels: {
        pt: 'IKE Lifetime (s)',
        en: 'IKE Lifetime (s)',
        es: 'Vida IKE (s)',
      },
      type: 'number',
      min: 3600,
      max: 86400,
    },
    {
      key: 'saLifetime',
      label: 'SA Lifetime (s)',
      labels: {
        pt: 'SA Lifetime (s)',
        en: 'SA Lifetime (s)',
        es: 'Vida SA (s)',
      },
      type: 'number',
      min: 300,
      max: 86400,
    },
    {
      key: 'rekeyMargin',
      label: 'Renegociar (%)',
      labels: {
        pt: 'Renegociar (%)',
        en: 'Rekey Margin (%)',
        es: 'Margen Rekey (%)',
      },
      type: 'number',
      min: 5,
      max: 50,
    },
    {
      key: 'dhGroup',
      label: 'Grupo DH',
      labels: { pt: 'Grupo DH', en: 'DH Group', es: 'Grupo DH' },
      type: 'select',
      options: ['group-14', 'group-19', 'group-20', 'group-21'],
    },
    {
      key: 'integrity',
      label: 'Integridade',
      labels: { pt: 'Integridade', en: 'Integrity', es: 'Integridad' },
      type: 'select',
      options: ['sha-256', 'sha-384', 'sha-512', 'md5'],
    },
    {
      key: 'prf',
      label: 'PRF',
      labels: { pt: 'PRF', en: 'PRF', es: 'PRF' },
      type: 'select',
      options: ['sha-256', 'sha-384', 'sha-512'],
    },
    {
      key: 'compression',
      label: 'Compressão',
      labels: { pt: 'Compressão', en: 'Compression', es: 'Compresión' },
      type: 'select',
      options: ['none', 'lz4', 'deflate'],
    },
    // SSL-VPN specific — visível quando tunnelType = ssl-remote
    {
      key: 'tlsVersion',
      label: 'TLS',
      labels: { pt: 'Versão TLS', en: 'TLS Version', es: 'Versión TLS' },
      type: 'select',
      options: ['1.2', '1.3'],
      visibleWhen: { tunnelType: 'ssl-remote' },
    },
    {
      key: 'sessionResumption',
      label: 'Session Resumption',
      labels: {
        pt: 'Session Resumption',
        en: 'Session Resumption',
        es: 'Reanudación de Sesión',
      },
      type: 'boolean',
      visibleWhen: { tunnelType: 'ssl-remote' },
    },
    {
      key: 'idleTimeout',
      label: 'Idle Timeout (s)',
      labels: {
        pt: 'Idle Timeout (s)',
        en: 'Idle Timeout (s)',
        es: 'Timeout Inactivo (s)',
      },
      type: 'number',
      min: 60,
      max: 86400,
      visibleWhen: { tunnelType: 'ssl-remote' },
    },
    {
      key: 'maxSessions',
      label: 'Máx. Sessões',
      labels: { pt: 'Máx. Sessões', en: 'Max Sessions', es: 'Máx. Sesiones' },
      type: 'number',
      min: 1,
      max: 100000,
      visibleWhen: { tunnelType: 'ssl-remote' },
    },
    {
      key: 'failoverPolicy',
      label: 'Failover',
      labels: { pt: 'Failover', en: 'Failover', es: 'Failover' },
      type: 'select',
      options: ['manual', 'active-passive', 'active-active'],
    },
  ],
  ids: [
    {
      key: 'inspectionMode',
      label: 'Modo',
      labels: { pt: 'Modo', en: 'Mode', es: 'Modo' },
      type: 'select',
      options: ['ids', 'ips'],
    },
    {
      key: 'signatureProfile',
      label: 'Perfil de Assinatura',
      labels: {
        pt: 'Perfil de Assinatura',
        en: 'Signature Profile',
        es: 'Perfil de Firma',
      },
      type: 'select',
      options: ['balanced', 'strict', 'custom'],
    },
    {
      key: 'anomalyDetection',
      label: 'Deteccao de Anomalia',
      labels: {
        pt: 'Detecção de Anomalia',
        en: 'Anomaly Detection',
        es: 'Detección de Anomalía',
      },
      type: 'boolean',
    },
    {
      key: 'responseAction',
      label: 'Acao',
      labels: { pt: 'Ação', en: 'Action', es: 'Acción' },
      type: 'select',
      options: ['alert', 'drop', 'quarantine'],
    },
    {
      key: 'feedUpdate',
      label: 'Atualizacao de Feed',
      labels: {
        pt: 'Atualização de Feed',
        en: 'Feed Update',
        es: 'Actualización de Feed',
      },
      type: 'select',
      options: ['auto', 'manual'],
    },
  ],
  'access-point': [
    {
      key: 'ssid',
      label: 'SSID',
      labels: { pt: 'SSID', en: 'SSID', es: 'SSID' },
      type: 'text',
    },
    {
      key: 'band',
      label: 'Banda',
      labels: { pt: 'Banda', en: 'Band', es: 'Banda' },
      type: 'select',
      options: ['2.4GHz', '5GHz', '6GHz', 'dual-band'],
    },
    {
      key: 'channelWidth',
      label: 'Largura de Canal',
      labels: {
        pt: 'Largura de Canal',
        en: 'Channel Width',
        es: 'Ancho de Canal',
      },
      type: 'select',
      options: ['20MHz', '40MHz', '80MHz', '160MHz'],
    },
    {
      key: 'wirelessSecurity',
      label: 'Seguranca',
      labels: { pt: 'Segurança', en: 'Security', es: 'Seguridad' },
      type: 'select',
      options: ['wpa2-psk', 'wpa3-psk', 'wpa2-enterprise', 'wpa3-enterprise'],
    },
    {
      key: 'authServer',
      label: 'Servidor AAA',
      labels: { pt: 'Servidor AAA', en: 'AAA Server', es: 'Servidor AAA' },
      type: 'text',
      visibleWhen: {
        wirelessSecurity: [
          'wpa2-enterprise',
          'wpa3-enterprise',
        ] satisfies TechValue[],
      },
    },
    {
      key: 'vlanMapping',
      label: 'Mapeamento VLAN',
      labels: {
        pt: 'Mapeamento VLAN',
        en: 'VLAN Mapping',
        es: 'Asignación VLAN',
      },
      type: 'text',
    },
    {
      key: 'controllerMode',
      label: 'Modo de Controle',
      labels: {
        pt: 'Modo de Controle',
        en: 'Controller Mode',
        es: 'Modo de Controlador',
      },
      type: 'select',
      options: ['standalone', 'managed'],
    },
    {
      key: 'guestIsolation',
      label: 'Isolamento Cliente',
      labels: {
        pt: 'Isolamento de Cliente',
        en: 'Guest Isolation',
        es: 'Aislamiento de Invitados',
      },
      type: 'boolean',
    },
  ],
  printer: [
    {
      key: 'printerProtocol',
      label: 'Protocolo',
      labels: { pt: 'Protocolo', en: 'Protocol', es: 'Protocolo' },
      type: 'select',
      options: ['tcp-ip', 'ipp', 'lpr'],
    },
    {
      key: 'queueName',
      label: 'Fila',
      labels: { pt: 'Fila', en: 'Queue', es: 'Cola' },
      type: 'text',
    },
    {
      key: 'dhcpReserved',
      label: 'DHCP Reservado',
      labels: {
        pt: 'DHCP Reservado',
        en: 'DHCP Reserved',
        es: 'DHCP Reservado',
      },
      type: 'boolean',
    },
    {
      key: 'snmpEnabled',
      label: 'SNMP',
      labels: { pt: 'SNMP', en: 'SNMP', es: 'SNMP' },
      type: 'boolean',
    },
  ],
  generic: [
    {
      key: 'role',
      label: 'Funcao',
      labels: { pt: 'Função', en: 'Role', es: 'Función' },
      type: 'text',
    },
  ],
};

export const DEFAULT_TECH_FIELDS_BY_KIND: Record<
  TechKind,
  (context: TechProfileContext) => Record<string, TechValue>
> = {
  router: (context) => ({
    gatewayDefault: context.shouldBeGateway,
    routingMode: context.layerOrder === 1 ? 'ospf' : 'static',
    natMode: context.layerOrder === 1 ? 'pat' : 'none',
    stateMode: 'stateful',
    wanUplink: 'ethernet-1g',
    qosEnabled: false,
    dscpMarking: false,
  }),
  firewall: (context) => ({
    gatewayDefault: context.shouldBeGateway,
    natMode: 'pat',
    stateMode: 'stateful',
    defaultPolicy: 'deny',
    idsIpsIntegration: 'none',
    sessionTimeout: 3600,
    maxConnections: 10000,
  }),
  vpn: (context) => ({
    tunnelType:
      {
        vpn: 'ipsec-site-to-site',
        ipsec: 'ipsec-site-to-site',
        wireguard: 'wireguard',
        sdwan: 'sdwan',
        mpls: 'mpls',
        gre: 'gre',
      }[context.category] ?? 'ipsec-site-to-site',
    encryptionSuite: 'aes-256-gcm',
    authMethod: 'psk',
    ikeVersion:
      context.category === 'gre' || context.category === 'mpls'
        ? 'n-a'
        : 'ikev2',
    remotePeer: 'peer.example.net',
    dpdKeepalive: true,
    dpdInterval: 10,
    dpdRetries: 3,
    ikeLifetime: 86400,
    saLifetime: 3600,
    rekeyMargin: 10,
    dhGroup: 'group-19',
    integrity: 'sha-256',
    prf: 'sha-256',
    compression: 'none',
    failoverPolicy: 'active-passive',
    // SSL-VPN defaults
    tlsVersion: '1.3',
    sessionResumption: true,
    idleTimeout: 300,
    maxSessions: 100,
  }),
  ids: (context) => ({
    inspectionMode: context.category === 'ips' ? 'ips' : 'ids',
    signatureProfile: 'balanced',
    anomalyDetection: true,
    responseAction: context.category === 'ips' ? 'drop' : 'alert',
    feedUpdate: 'auto',
  }),
  'access-point': () => ({
    ssid: 'CorpWiFi',
    band: 'dual-band',
    channelWidth: '40MHz',
    wirelessSecurity: 'wpa2-enterprise',
    authServer: 'radius.site.local',
    vlanMapping: '40',
    controllerMode: 'managed',
    guestIsolation: true,
  }),
  printer: () => ({
    printerProtocol: 'tcp-ip',
    queueName: 'PRN-CORP',
    dhcpReserved: true,
    snmpEnabled: true,
  }),
  generic: (context) => ({
    role: context.category,
  }),
};
