import type { RouteEntry, RouteType } from '../../../types/network'

export const TYPE_CLASS: Record<RouteType, string> = {
  Direta: 'rt-type-direct',
  Estática: 'rt-type-static',
  Default: 'rt-type-default',
}

export const SP_ROUTES: RouteEntry[] = [
  {
    type: 'Direta',
    destination: '10.10.0.0',
    mask: '/16',
    gateway: '—',
    metric: '—',
    iface: 'core0 - LAN Matriz',
    ifaceColor: 'var(--green)',
  },
  {
    type: 'Direta',
    destination: '203.0.113.0',
    mask: '/30',
    gateway: '—',
    metric: '—',
    iface: 'wan1 - MPLS',
    ifaceColor: 'var(--orange)',
  },
  {
    type: 'Direta',
    destination: '198.51.100.0',
    mask: '/30',
    gateway: '—',
    metric: '—',
    iface: 'wan2 - Internet',
    ifaceColor: 'var(--cyan)',
  },
  {
    type: 'Estática',
    destination: 'Redes da Filial',
    mask: '/24,/25,/26,/28',
    gateway: '203.0.113.2',
    metric: '10',
    iface: 'wan1 - MPLS (metrica 10)',
    ifaceColor: 'var(--purple)',
  },
  {
    type: 'Default',
    destination: '0.0.0.0',
    mask: '/0',
    gateway: '203.0.113.2',
    metric: '10',
    iface: 'wan1 - MPLS (primario)',
    ifaceColor: 'var(--orange)',
  },
  {
    type: 'Default',
    destination: '0.0.0.0',
    mask: '/0',
    gateway: '198.51.100.2',
    metric: '20',
    iface: 'wan2 - VPN IPsec (metrica 20)',
    ifaceColor: 'var(--cyan)',
  },
]

export const CWB_ROUTES: RouteEntry[] = [
  {
    type: 'Direta',
    destination: 'Redes locais da Filial',
    mask: '/24,/25,/26,/28',
    gateway: '—',
    metric: '—',
    iface: 'lan0 - VLANs Filial',
    ifaceColor: 'var(--green)',
  },
  {
    type: 'Direta',
    destination: '203.0.113.4',
    mask: '/30',
    gateway: '—',
    metric: '—',
    iface: 'wan1 - MPLS',
    ifaceColor: 'var(--orange)',
  },
  {
    type: 'Direta',
    destination: '198.51.100.4',
    mask: '/30',
    gateway: '—',
    metric: '—',
    iface: 'wan2 - Internet',
    ifaceColor: 'var(--cyan)',
  },
  {
    type: 'Estática',
    destination: '10.10.0.0',
    mask: '/16',
    gateway: '203.0.113.6',
    metric: '10',
    iface: 'wan1 - MPLS (metrica 10)',
    ifaceColor: 'var(--purple)',
  },
  {
    type: 'Default',
    destination: '0.0.0.0',
    mask: '/0',
    gateway: '203.0.113.6',
    metric: '10',
    iface: 'wan1 - MPLS (primario)',
    ifaceColor: 'var(--orange)',
  },
  {
    type: 'Default',
    destination: '0.0.0.0',
    mask: '/0',
    gateway: '198.51.100.1',
    metric: '20',
    iface: 'wan2 - VPN IPsec (metrica 20)',
    ifaceColor: 'var(--cyan)',
  },
]
