import * as go from 'gojs';

export const ICON_KEYS_BY_LAYER = {
  layer1: ['rtr', 'fw'],
  layer2: ['sw'],
  layer3: ['srv', 'ap'],
  layer4: ['pc', 'printer', 'phone', 'mobile'],
} as const;

export const MAX_ICONS_IN_ANY_LAYER = Math.max(
  ...Object.values(ICON_KEYS_BY_LAYER).map((keys) => keys.length),
);

export const ICON_SLOT_WIDTH = 140;
export const CONTAINER_SIDE_MIN_MARGIN = 5;
export const MAIN_CONTAINER_WIDTH =
  MAX_ICONS_IN_ANY_LAYER * ICON_SLOT_WIDTH + CONTAINER_SIDE_MIN_MARGIN * 2;
export const MAIN_CONTAINER_MIN_HEIGHT = 469;
export const MAIN_CONTAINER_MAX_HEIGHT = 820;
export const PLACEHOLDER_PADDING = 16;

export const LAYER_SIDE_MARGIN = 12;
export const LAYER_WIDTH = MAIN_CONTAINER_WIDTH - LAYER_SIDE_MARGIN * 2;
export const LAYER_GAP = 12;
export const LAYER1_Y = -210;
export const LAYER1_HEIGHT = 248;
export const LAYER_COMMON_HEIGHT = 120;
export const LAYER2_Y = LAYER1_Y + LAYER1_HEIGHT + LAYER_GAP;
export const LAYER3_Y = LAYER2_Y + LAYER_COMMON_HEIGHT + LAYER_GAP;
export const LAYER4_Y = LAYER3_Y + LAYER_COMMON_HEIGHT + LAYER_GAP;

export const DIAGRAM_NODE_DATA = [
  {
    key: 'g-sp',
    isGroup: true,
    text: 'Matriz SP - Bloco corporativo 10.10.0.0/16',
    loc: '-500 -230',
    stroke: '#2d7fff',
    fill: 'rgba(10, 30, 56, 0.45)',
  },
  {
    key: 'g-cwb',
    isGroup: true,
    text: 'Filial CWB - Sub-redes por crescimento + reserva',
    loc: '169 -230',
    stroke: '#00c97a',
    fill: 'rgba(10, 42, 29, 0.45)',
  },

  {
    key: 'sp-layer-core',
    category: 'layerbox',
    text: 'Core - WAN + Seguranca',
    loc: '-530 -210',
    size: `${LAYER_WIDTH} 190`,
    group: 'g-sp',
  },
  {
    key: 'sp-layer-dist',
    category: 'layerbox',
    text: 'Distribuicao - 4x Catalyst 9300 (L3)',
    loc: '-530 -8',
    size: `${LAYER_WIDTH} 90`,
    group: 'g-sp',
  },
  {
    key: 'sp-layer-acc',
    category: 'layerbox',
    text: 'Acesso - 20x Catalyst 9200 (L2)',
    loc: '-530 94',
    size: `${LAYER_WIDTH} 120`,
    group: 'g-sp',
  },
  {
    key: 'sp-layer-end',
    category: 'layerbox',
    text: 'Endpoints (representacao visual)',
    loc: '-530 226',
    size: `${LAYER_WIDTH} 150`,
    group: 'g-sp',
  },

  {
    key: 'sp-rtr',
    type: 'Router',
    text: 'Roteador Matriz\n203.0.113.1/30',
    loc: '-355 -170',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '203.0.113.1/30 | 2001:db8:a001::1/126',
    vlan: 'WAN primario MPLS (100 Mbps, SLA 99,9%)',
    vlanInfo: 'Link principal para comunicacao com filiais e rota default operacional.',
  },
  {
    key: 'sp-fw',
    type: 'Firewall',
    text: 'FortiGate 600F\nHA Active-Passive',
    loc: '-355 -50',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: 'Borda segura da Matriz',
    vlan: 'Controle inter-VLAN + politicas de borda',
    vlanInfo: 'HA Active-Passive, NAT, ACL, inspecao e terminacao de VPN.',
  },
  {
    key: 'sp-sw',
    type: 'Switch',
    text: 'Core Catalyst 9500\nInter-VLAN L3',
    loc: '-355 37',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.10.0.0/16',
    vlan: '10,20,30,40,50,60,70,80,99',
    vlanInfo: 'Core L3 da arquitetura formal em 3 camadas; atende ~1.000 usuarios e ~20 servidores.',
  },
  {
    key: 'sp-srv',
    type: 'Server',
    text: 'Servidores Producao',
    loc: '-450 154',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.10.10.0/24',
    vlan: 'VLAN 10',
    vlanInfo: 'Aplicacoes e servicos corporativos',
  },
  {
    key: 'sp-ap',
    type: 'AP',
    text: 'Wi-Fi Corporativo',
    loc: '-260 154',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.10.70.0/24',
    vlan: 'VLAN 70',
    vlanInfo: 'Acesso sem fio corporativo',
  },
  {
    key: 'sp-pc',
    type: 'PC',
    text: 'Desenvolvimento',
    loc: '-500 275',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.10.40.0/23',
    vlan: 'VLAN 40',
    vlanInfo: 'Workstations de desenvolvimento',
  },
  {
    key: 'sp-printer',
    type: 'Printer',
    text: 'Administrativo',
    loc: '-405 275',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.10.50.0/23',
    vlan: 'VLAN 50',
    vlanInfo: 'Operacao administrativa',
  },
  {
    key: 'sp-phone',
    type: 'Phone',
    text: 'Comercial / Suporte',
    loc: '-310 275',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.10.60.0/23',
    vlan: 'VLAN 60',
    vlanInfo: 'Atendimento e operacao comercial',
  },
  {
    key: 'sp-mobile',
    type: 'Mobile',
    text: 'Wi-Fi Visitantes',
    loc: '-215 275',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.10.80.0/24',
    vlan: 'VLAN 80',
    vlanInfo: 'Rede isolada para visitantes',
  },

  {
    key: 'wan',
    type: 'Cloud',
    text: 'WAN MPLS + Internet',
    loc: '-10 -260',
    site: 'Core central',
    ip: 'MPLS + Internet dedicada',
    vlan: 'Primario MPLS | Backup IPsec',
    vlanInfo: 'MPLS em dual-stack; contingencia IPsec em IPv4-only.',
  },
  {
    key: 'vpn-sts',
    type: 'VPN',
    text: 'IPsec Backup\n198.51.100.0/30',
    loc: '-10 -55',
    site: 'Core central',
    ip: '198.51.100.1 <-> 198.51.100.5',
    vlan: 'Metrica 20 | 50 Mbps | IPv4 only',
    vlanInfo: 'Ativacao automatica em falha MPLS com convergencia estimada de 15-30s.',
  },
  {
    key: 'vpn-ssl',
    type: 'VPN',
    text: 'SSL-VPN Remoto\n10.10.1.0/28',
    loc: '-10 35',
    site: 'Core central',
    ip: '10.10.1.0/28',
    vlan: 'N/A',
    vlanInfo: 'Acesso remoto de usuarios',
  },
  {
    key: 'pc-externo',
    type: 'PC',
    text: 'PCs Externos\nAcesso VPN',
    loc: '-10 275',
    site: 'Remoto',
    ip: 'Cliente VPN',
    vlan: 'N/A',
    vlanInfo: 'Origem do acesso remoto SSL',
  },

  {
    key: 'cwb-layer-core',
    category: 'layerbox',
    text: 'Core - WAN + Seguranca',
    loc: '119 -210',
    size: `${LAYER_WIDTH} 190`,
    group: 'g-cwb',
  },
  {
    key: 'cwb-layer-dist',
    category: 'layerbox',
    text: 'Distribuicao - Segmentacao por VLAN',
    loc: '119 -8',
    size: `${LAYER_WIDTH} 90`,
    group: 'g-cwb',
  },
  {
    key: 'cwb-layer-acc',
    category: 'layerbox',
    text: 'Acesso - Usuarios, servidores e Wi-Fi',
    loc: '119 94',
    size: `${LAYER_WIDTH} 120`,
    group: 'g-cwb',
  },
  {
    key: 'cwb-layer-end',
    category: 'layerbox',
    text: 'Endpoints (representacao visual)',
    loc: '119 226',
    size: `${LAYER_WIDTH} 150`,
    group: 'g-cwb',
  },

  {
    key: 'cwb-rtr',
    type: 'Router',
    text: 'Gateway Filial MPLS\n203.0.113.5/30',
    loc: '334 -170',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '203.0.113.5/30 | 2001:db8:a002::1/126',
    vlan: 'WAN primario MPLS (100 Mbps, SLA 99,9%)',
    vlanInfo: 'Conectividade principal da filial com fallback para VPN de contingencia.',
  },
  {
    key: 'cwb-fw',
    type: 'Firewall',
    text: 'Firewall Filial\nACL/NAT/IPsec',
    loc: '334 -50',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: 'Borda segura da Filial',
    vlan: 'Controle de acesso entre segmentos locais e matriz',
    vlanInfo: 'NAT, ACL e terminação IPsec IKEv2 no enlace de backup.',
  },
  {
    key: 'cwb-sw',
    type: 'Switch',
    text: 'Switch Filial\nSegmentacao por demanda',
    loc: '334 37',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: 'Sub-redes /24, /25, /26 e /28',
    vlan: 'Desenv, Suporte, Adm, TI, Servidores',
    vlanInfo: 'Dimensionado para 3 anos +20% de reserva operacional (alvo de 360 usuarios).',
  },
  {
    key: 'cwb-srv',
    type: 'Server',
    text: 'Servidores Filial',
    loc: '239 154',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: 'Inicial 4 (expansao 6-8)',
    vlan: 'VLAN dedicada de servidores',
    vlanInfo: 'AD Replica, File, Print e Backup',
  },
  {
    key: 'cwb-ap',
    type: 'AP',
    text: 'Wi-Fi Corp + Visitantes',
    loc: '429 154',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: 'SSID corporativo e visitantes',
    vlan: 'Isolamento logico obrigatorio',
    vlanInfo: 'Visitantes sem acesso a rede interna',
  },
  {
    key: 'cwb-pc',
    type: 'PC',
    text: 'Desenvolvimento (Filial)',
    loc: '194 275',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '144 hosts (com reserva)',
    vlan: 'Prefixo /24',
    vlanInfo: 'Crescimento +50% e buffer operacional',
  },
  {
    key: 'cwb-printer',
    type: 'Printer',
    text: 'Suporte + Administrativo',
    loc: '289 275',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '108 hosts + 72 hosts',
    vlan: 'Prefixos /25',
    vlanInfo: 'Departamentos com escala moderada',
  },
  {
    key: 'cwb-phone',
    type: 'Phone',
    text: 'TI / Infraestrutura',
    loc: '384 275',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '36 hosts com reserva',
    vlan: 'Prefixo /26',
    vlanInfo: 'Gestao de infraestrutura local',
  },
  {
    key: 'cwb-mobile',
    type: 'Mobile',
    text: 'VLAN de Gerencia',
    loc: '479 275',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: 'Rede de equipamentos gerenciados',
    vlan: 'Switches, APs e ativos de rede',
    vlanInfo: 'Acesso restrito a equipe de TI',
  },
] as Array<Record<string, unknown>>;

export const DIAGRAM_LINK_DATA = [
  { from: 'sp-rtr', to: 'sp-fw', label: 'Core/WAN', stroke: '#c98a5e' },
  { from: 'sp-fw', to: 'sp-sw', label: 'Distribuicao', stroke: '#2d7fff' },
  { from: 'sp-sw', to: 'sp-srv', label: 'Acesso' },
  { from: 'sp-sw', to: 'sp-ap', label: 'Acesso' },
  { from: 'sp-sw', to: 'sp-pc', label: 'Endpoint' },
  { from: 'sp-sw', to: 'sp-printer', label: 'Endpoint' },
  { from: 'sp-sw', to: 'sp-phone', label: 'Endpoint' },
  {
    from: 'sp-pc',
    to: 'sp-srv',
    label: 'LAN',
    stroke: '#6ca2db',
    dash: [2, 3],
  },
  {
    from: 'sp-printer',
    to: 'sp-srv',
    label: 'LAN',
    stroke: '#6ca2db',
    dash: [2, 3],
  },
  {
    from: 'sp-pc',
    to: 'sp-ap',
    label: 'Wi-Fi acesso',
    stroke: '#2aa9c2',
    dash: [2, 3],
  },
  {
    from: 'sp-printer',
    to: 'sp-ap',
    label: 'Wi-Fi impressao',
    stroke: '#2aa9c2',
    dash: [2, 3],
  },
  {
    from: 'sp-mobile',
    to: 'sp-ap',
    label: 'Wi-Fi celular',
    stroke: '#2aa9c2',
    dash: [2, 3],
    fromSpot: 'Top',
  },
  {
    from: 'sp-mobile',
    to: 'sp-srv',
    label: 'App interna',
    stroke: '#6ca2db',
    dash: [2, 3],
    fromSpot: 'Left',
  },
  {
    from: 'sp-mobile',
    to: 'wan',
    label: 'Internet',
    stroke: '#2aa9c2',
    dash: [2, 3],
    fromSpot: 'Right',
  },

  { from: 'cwb-rtr', to: 'cwb-fw', label: 'Core/WAN', stroke: '#4db17a' },
  {
    from: 'cwb-fw',
    to: 'cwb-sw',
    label: 'Distribuicao',
    stroke: '#00c97a',
  },
  { from: 'cwb-sw', to: 'cwb-srv', label: 'Acesso' },
  { from: 'cwb-sw', to: 'cwb-ap', label: 'Acesso' },
  { from: 'cwb-sw', to: 'cwb-pc', label: 'Endpoint' },
  { from: 'cwb-sw', to: 'cwb-printer', label: 'Endpoint' },
  { from: 'cwb-sw', to: 'cwb-phone', label: 'Endpoint' },
  {
    from: 'cwb-pc',
    to: 'cwb-srv',
    label: 'LAN',
    stroke: '#6ec898',
    dash: [2, 3],
  },
  {
    from: 'cwb-printer',
    to: 'cwb-srv',
    label: 'LAN',
    stroke: '#6ec898',
    dash: [2, 3],
  },
  {
    from: 'cwb-pc',
    to: 'cwb-ap',
    label: 'Wi-Fi acesso',
    stroke: '#2aa9c2',
    dash: [2, 3],
  },
  {
    from: 'cwb-printer',
    to: 'cwb-ap',
    label: 'Wi-Fi impressao',
    stroke: '#2aa9c2',
    dash: [2, 3],
  },
  {
    from: 'cwb-mobile',
    to: 'cwb-ap',
    label: 'Wi-Fi celular',
    stroke: '#2aa9c2',
    dash: [2, 3],
    fromSpot: 'Top',
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 26,
  },
  {
    from: 'cwb-mobile',
    to: 'cwb-srv',
    label: 'App interna',
    stroke: '#6ec898',
    dash: [2, 3],
    fromSpot: 'Left',
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 34,
  },
  {
    from: 'cwb-mobile',
    to: 'wan',
    label: 'Internet',
    stroke: '#2aa9c2',
    dash: [2, 3],
    fromSpot: 'Right',
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 42,
  },

  {
    from: 'wan',
    to: 'sp-rtr',
    label: 'MPLS Matriz',
    stroke: '#ad6f38',
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 18,
    toEndSegmentLength: 24,
    fromSpot: 'Left',
    toSpot: 'Top',
    infoTitle: 'Link Primario MPLS - Matriz',
    infoSite: 'Operadora A | Matriz SP (wan1)',
    infoIp: 'IPv4 203.0.113.1/30 | IPv6 2001:db8:a001::1/126',
    infoVlan: '100 Mbps | SLA 99,9% | Metrica 10',
    infoText:
      'Canal preferencial para comunicacao com filiais e trafego corporativo em operacao normal.',
  },
  {
    from: 'wan',
    to: 'cwb-rtr',
    label: 'MPLS Filial',
    stroke: '#2f9560',
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 18,
    toEndSegmentLength: 24,
    fromSpot: 'Right',
    toSpot: 'Top',
    infoTitle: 'Link Primario MPLS - Filial',
    infoSite: 'Operadora A | Filial CWB (wan1)',
    infoIp: 'IPv4 203.0.113.5/30 | IPv6 2001:db8:a002::1/126',
    infoVlan: '100 Mbps simetrico | SLA 99,9% | Metrica 10',
    infoText:
      'Rota preferencial da filial para matriz e servicos corporativos em dual-stack.',
  },
  {
    from: 'sp-fw',
    to: 'vpn-sts',
    label: 'IPsec backup',
    stroke: '#49c277',
    dash: [6, 2],
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 16,
    toEndSegmentLength: 16,
    fromSpot: 'Right',
    toSpot: 'Left',
    infoTitle: 'IPsec Backup - Matriz para Túnel',
    infoSite: 'Operadora B | Borda Matriz',
    infoIp: '198.51.100.1/30 -> 198.51.100.5/30',
    infoVlan: '50 Mbps | Metrica 20 | IPv4 only',
    infoText:
      'Ativado automaticamente em falha MPLS. Em contingencia, servicos IPv6 ficam indisponiveis.',
  },
  {
    from: 'vpn-sts',
    to: 'cwb-fw',
    label: 'IPsec backup',
    stroke: '#49c277',
    dash: [6, 2],
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 16,
    toEndSegmentLength: 16,
    fromSpot: 'Right',
    toSpot: 'Left',
    infoTitle: 'IPsec Backup - Túnel para Filial',
    infoSite: 'Operadora B | Borda Filial',
    infoIp: '198.51.100.5/30 -> 198.51.100.1/30',
    infoVlan: 'IKEv2 | AES-256-GCM | SHA-384 | DH Group 20',
    infoText:
      'Canal de contingencia com convergencia estimada entre 15 e 30 segundos quando MPLS falha.',
  },
  {
    from: 'wan',
    to: 'vpn-ssl',
    label: 'SSL',
    stroke: '#7f5bc0',
    dash: [2, 2],
  },
  {
    from: 'pc-externo',
    to: 'vpn-ssl',
    label: 'Usuario remoto',
    stroke: '#7f5bc0',
    dash: [4, 2],
  },
  {
    from: 'vpn-ssl',
    to: 'sp-srv',
    label: 'VPN -> Servidores SP',
    stroke: '#7f5bc0',
    dash: [4, 2],
  },
  {
    from: 'vpn-ssl',
    to: 'cwb-srv',
    label: 'VPN -> Servidores CWB',
    stroke: '#7f5bc0',
    dash: [4, 2],
  },
] as Array<Record<string, unknown>>;
