import * as go from 'gojs';

export const ICON_KEYS_BY_LAYER = {
  layer1: ['rtr', 'fw'],
  layer2: ['sw'],
  layer3: ['srv', 'ap'],
  layer4: ['pc', 'printer', 'phone', 'mobile'],
} as const;

export const MAX_ICONS_IN_ANY_LAYER = Math.max(
  ...Object.values(ICON_KEYS_BY_LAYER).map((keys) => keys.length),
);

export const ICON_SLOT_WIDTH = 140;
export const CONTAINER_SIDE_MIN_MARGIN = 5;
export const MAIN_CONTAINER_WIDTH =
  MAX_ICONS_IN_ANY_LAYER * ICON_SLOT_WIDTH + CONTAINER_SIDE_MIN_MARGIN * 2;
export const MAIN_CONTAINER_MIN_HEIGHT = 469;
export const MAIN_CONTAINER_MAX_HEIGHT = 820;
export const PLACEHOLDER_PADDING = 16;

export const LAYER_SIDE_MARGIN = 12;
export const LAYER_WIDTH = MAIN_CONTAINER_WIDTH - LAYER_SIDE_MARGIN * 2;
export const LAYER_GAP = 12;
export const LAYER1_Y = -210;
export const LAYER1_HEIGHT = 248;
export const LAYER_COMMON_HEIGHT = 120;
export const LAYER2_Y = LAYER1_Y + LAYER1_HEIGHT + LAYER_GAP;
export const LAYER3_Y = LAYER2_Y + LAYER_COMMON_HEIGHT + LAYER_GAP;
export const LAYER4_Y = LAYER3_Y + LAYER_COMMON_HEIGHT + LAYER_GAP;

export const DIAGRAM_NODE_DATA = [
  {
    key: 'g-sp',
    isGroup: true,
    text: 'Matriz SP - Dominio 10.0.1.0/24',
    loc: '-500 -230',
    stroke: '#2d7fff',
    fill: 'rgba(10, 30, 56, 0.45)',
  },
  {
    key: 'g-cwb',
    isGroup: true,
    text: 'Filial CWB - Dominio 10.0.2.0/25',
    loc: '169 -230',
    stroke: '#00c97a',
    fill: 'rgba(10, 42, 29, 0.45)',
  },

  {
    key: 'sp-layer-core',
    category: 'layerbox',
    text: 'Camada 1 - Roteador + Firewall',
    loc: '-530 -210',
    size: `${LAYER_WIDTH} 190`,
    group: 'g-sp',
  },
  {
    key: 'sp-layer-dist',
    category: 'layerbox',
    text: 'Camada 2 - Switch',
    loc: '-530 -8',
    size: `${LAYER_WIDTH} 90`,
    group: 'g-sp',
  },
  {
    key: 'sp-layer-acc',
    category: 'layerbox',
    text: 'Camada 3 - Servidores + Access Point',
    loc: '-530 94',
    size: `${LAYER_WIDTH} 120`,
    group: 'g-sp',
  },
  {
    key: 'sp-layer-end',
    category: 'layerbox',
    text: 'Camada 4 - Dispositivos',
    loc: '-530 226',
    size: `${LAYER_WIDTH} 150`,
    group: 'g-sp',
  },

  {
    key: 'sp-rtr',
    type: 'Router',
    text: 'Roteador Matriz\n200.10.1.1/30',
    loc: '-355 -170',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '200.10.1.1/30',
    vlan: 'Backbone',
    vlanInfo: 'Uplink WAN da Matriz',
  },
  {
    key: 'sp-fw',
    type: 'Firewall',
    text: 'Firewall Matriz\nACL/NAT/VPN',
    loc: '-355 -50',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: 'Gateway interno',
    vlan: 'Trunk 10/20/30/40',
    vlanInfo: 'NAT, ACL e VPN',
  },
  {
    key: 'sp-sw',
    type: 'Switch',
    text: 'Switch L3 Matriz\n10.0.1.2',
    loc: '-355 37',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.0.1.2',
    vlan: '10, 20, 30, 40',
    vlanInfo: 'SVIs e distribuicao local',
  },
  {
    key: 'sp-srv',
    type: 'Server',
    text: 'Servidores SP (3)',
    loc: '-450 154',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.0.1.200-202',
    vlan: 'VLAN 30',
    vlanInfo: 'Servicos internos e aplicacoes',
  },
  {
    key: 'sp-ap',
    type: 'AP',
    text: 'Access Point SP',
    loc: '-260 154',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.0.1.70-80',
    vlan: 'VLAN 40',
    vlanInfo: 'SSID corporativo e mobilidade',
  },
  {
    key: 'sp-pc',
    type: 'PC',
    text: 'PCs SP (21)',
    loc: '-500 275',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.0.1.10-30',
    vlan: 'VLAN 10',
    vlanInfo: 'Estacoes de trabalho de dados',
  },
  {
    key: 'sp-printer',
    type: 'Printer',
    text: 'Impressoras SP (3)',
    loc: '-405 275',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.0.1.31-40',
    vlan: 'VLAN 10',
    vlanInfo: 'Fila de impressao corporativa',
  },
  {
    key: 'sp-phone',
    type: 'Phone',
    text: 'Telefones SP (6)',
    loc: '-310 275',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.0.1.50-55',
    vlan: 'VLAN 20',
    vlanInfo: 'Servico de voz IP',
  },
  {
    key: 'sp-mobile',
    type: 'Mobile',
    text: 'Celulares SP',
    loc: '-215 275',
    group: 'g-sp',
    site: 'Matriz SP',
    ip: '10.0.1.81-95',
    vlan: 'VLAN 40',
    vlanInfo: 'Acesso wireless e internet',
  },

  {
    key: 'wan',
    type: 'Cloud',
    text: 'WAN / Internet',
    loc: '-10 -260',
    site: 'Core central',
    ip: 'Transit publico',
    vlan: 'N/A',
    vlanInfo: 'Nuvem de transporte externo',
  },
  {
    key: 'vpn-sts',
    type: 'VPN',
    text: 'IPsec Site-to-Site\n10.10.0.0/30',
    loc: '-10 -55',
    site: 'Core central',
    ip: '10.10.0.0/30',
    vlan: 'N/A',
    vlanInfo: 'Tunel IPsec Matriz <-> Filial',
  },
  {
    key: 'vpn-ssl',
    type: 'VPN',
    text: 'SSL-VPN Remoto\n10.10.1.0/28',
    loc: '-10 35',
    site: 'Core central',
    ip: '10.10.1.0/28',
    vlan: 'N/A',
    vlanInfo: 'Acesso remoto de usuarios',
  },
  {
    key: 'pc-externo',
    type: 'PC',
    text: 'PCs Externos\nAcesso VPN',
    loc: '-10 275',
    site: 'Remoto',
    ip: 'Cliente VPN',
    vlan: 'N/A',
    vlanInfo: 'Origem do acesso remoto SSL',
  },

  {
    key: 'cwb-layer-core',
    category: 'layerbox',
    text: 'Camada 1 - Roteador + Firewall',
    loc: '119 -210',
    size: `${LAYER_WIDTH} 190`,
    group: 'g-cwb',
  },
  {
    key: 'cwb-layer-dist',
    category: 'layerbox',
    text: 'Camada 2 - Switch',
    loc: '119 -8',
    size: `${LAYER_WIDTH} 90`,
    group: 'g-cwb',
  },
  {
    key: 'cwb-layer-acc',
    category: 'layerbox',
    text: 'Camada 3 - Servidores + Access Point',
    loc: '119 94',
    size: `${LAYER_WIDTH} 120`,
    group: 'g-cwb',
  },
  {
    key: 'cwb-layer-end',
    category: 'layerbox',
    text: 'Camada 4 - Dispositivos',
    loc: '119 226',
    size: `${LAYER_WIDTH} 150`,
    group: 'g-cwb',
  },

  {
    key: 'cwb-rtr',
    type: 'Router',
    text: 'Roteador Filial\n200.20.1.1/30',
    loc: '334 -170',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '200.20.1.1/30',
    vlan: 'Backbone',
    vlanInfo: 'Uplink WAN da Filial',
  },
  {
    key: 'cwb-fw',
    type: 'Firewall',
    text: 'Firewall Filial\nACL/NAT/VPN',
    loc: '334 -50',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: 'Gateway interno',
    vlan: 'Trunk 10/20/30/40',
    vlanInfo: 'NAT, ACL e VPN',
  },
  {
    key: 'cwb-sw',
    type: 'Switch',
    text: 'Switch L3 Filial\n10.0.2.2',
    loc: '334 37',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '10.0.2.2',
    vlan: '10, 20, 30, 40',
    vlanInfo: 'SVIs e distribuicao local',
  },
  {
    key: 'cwb-srv',
    type: 'Server',
    text: 'Servidores CWB (2)',
    loc: '239 154',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '10.0.2.200-201',
    vlan: 'VLAN 30',
    vlanInfo: 'Servicos locais da filial',
  },
  {
    key: 'cwb-ap',
    type: 'AP',
    text: 'Access Points CWB (4)',
    loc: '429 154',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '10.0.2.70-85',
    vlan: 'VLAN 40',
    vlanInfo: 'Rede wireless corporativa',
  },
  {
    key: 'cwb-pc',
    type: 'PC',
    text: 'PCs CWB (22)',
    loc: '194 275',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '10.0.2.10-31',
    vlan: 'VLAN 10',
    vlanInfo: 'Estacoes de trabalho da filial',
  },
  {
    key: 'cwb-printer',
    type: 'Printer',
    text: 'Impressoras CWB (4)',
    loc: '289 275',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '10.0.2.32-40',
    vlan: 'VLAN 10',
    vlanInfo: 'Impressao local e compartilhada',
  },
  {
    key: 'cwb-phone',
    type: 'Phone',
    text: 'Telefones CWB (8)',
    loc: '384 275',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '10.0.2.50-57',
    vlan: 'VLAN 20',
    vlanInfo: 'Telefonia IP da filial',
  },
  {
    key: 'cwb-mobile',
    type: 'Mobile',
    text: 'Celulares CWB',
    loc: '479 275',
    group: 'g-cwb',
    site: 'Filial CWB',
    ip: '10.0.2.86-95',
    vlan: 'VLAN 40',
    vlanInfo: 'Acesso wireless de mobilidade',
  },
] as Array<Record<string, unknown>>;

export const DIAGRAM_LINK_DATA = [
  { from: 'sp-rtr', to: 'sp-fw', label: 'Core/WAN', stroke: '#c98a5e' },
  { from: 'sp-fw', to: 'sp-sw', label: 'Distribuicao', stroke: '#2d7fff' },
  { from: 'sp-sw', to: 'sp-srv', label: 'Acesso' },
  { from: 'sp-sw', to: 'sp-ap', label: 'Acesso' },
  { from: 'sp-sw', to: 'sp-pc', label: 'Endpoint' },
  { from: 'sp-sw', to: 'sp-printer', label: 'Endpoint' },
  { from: 'sp-sw', to: 'sp-phone', label: 'Endpoint' },
  {
    from: 'sp-pc',
    to: 'sp-srv',
    label: 'LAN',
    stroke: '#6ca2db',
    dash: [2, 3],
  },
  {
    from: 'sp-printer',
    to: 'sp-srv',
    label: 'LAN',
    stroke: '#6ca2db',
    dash: [2, 3],
  },
  {
    from: 'sp-pc',
    to: 'sp-ap',
    label: 'Wi-Fi acesso',
    stroke: '#2aa9c2',
    dash: [2, 3],
  },
  {
    from: 'sp-printer',
    to: 'sp-ap',
    label: 'Wi-Fi impressao',
    stroke: '#2aa9c2',
    dash: [2, 3],
  },
  {
    from: 'sp-mobile',
    to: 'sp-ap',
    label: 'Wi-Fi celular',
    stroke: '#2aa9c2',
    dash: [2, 3],
    fromSpot: 'Top',
  },
  {
    from: 'sp-mobile',
    to: 'sp-srv',
    label: 'App interna',
    stroke: '#6ca2db',
    dash: [2, 3],
    fromSpot: 'Left',
  },
  {
    from: 'sp-mobile',
    to: 'wan',
    label: 'Internet',
    stroke: '#2aa9c2',
    dash: [2, 3],
    fromSpot: 'Right',
  },

  { from: 'cwb-rtr', to: 'cwb-fw', label: 'Core/WAN', stroke: '#4db17a' },
  {
    from: 'cwb-fw',
    to: 'cwb-sw',
    label: 'Distribuicao',
    stroke: '#00c97a',
  },
  { from: 'cwb-sw', to: 'cwb-srv', label: 'Acesso' },
  { from: 'cwb-sw', to: 'cwb-ap', label: 'Acesso' },
  { from: 'cwb-sw', to: 'cwb-pc', label: 'Endpoint' },
  { from: 'cwb-sw', to: 'cwb-printer', label: 'Endpoint' },
  { from: 'cwb-sw', to: 'cwb-phone', label: 'Endpoint' },
  {
    from: 'cwb-pc',
    to: 'cwb-srv',
    label: 'LAN',
    stroke: '#6ec898',
    dash: [2, 3],
  },
  {
    from: 'cwb-printer',
    to: 'cwb-srv',
    label: 'LAN',
    stroke: '#6ec898',
    dash: [2, 3],
  },
  {
    from: 'cwb-pc',
    to: 'cwb-ap',
    label: 'Wi-Fi acesso',
    stroke: '#2aa9c2',
    dash: [2, 3],
  },
  {
    from: 'cwb-printer',
    to: 'cwb-ap',
    label: 'Wi-Fi impressao',
    stroke: '#2aa9c2',
    dash: [2, 3],
  },
  {
    from: 'cwb-mobile',
    to: 'cwb-ap',
    label: 'Wi-Fi celular',
    stroke: '#2aa9c2',
    dash: [2, 3],
    fromSpot: 'Top',
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 26,
  },
  {
    from: 'cwb-mobile',
    to: 'cwb-srv',
    label: 'App interna',
    stroke: '#6ec898',
    dash: [2, 3],
    fromSpot: 'Left',
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 34,
  },
  {
    from: 'cwb-mobile',
    to: 'wan',
    label: 'Internet',
    stroke: '#2aa9c2',
    dash: [2, 3],
    fromSpot: 'Right',
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 42,
  },

  {
    from: 'wan',
    to: 'sp-rtr',
    label: 'WAN SP',
    stroke: '#ad6f38',
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 18,
    toEndSegmentLength: 24,
    fromSpot: 'Left',
    toSpot: 'Top',
  },
  {
    from: 'wan',
    to: 'cwb-rtr',
    label: 'WAN CWB',
    stroke: '#2f9560',
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 18,
    toEndSegmentLength: 24,
    fromSpot: 'Right',
    toSpot: 'Top',
  },
  {
    from: 'sp-fw',
    to: 'vpn-sts',
    label: 'IPsec',
    stroke: '#49c277',
    dash: [6, 2],
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 16,
    toEndSegmentLength: 16,
    fromSpot: 'Right',
    toSpot: 'Left',
  },
  {
    from: 'vpn-sts',
    to: 'cwb-fw',
    label: 'IPsec',
    stroke: '#49c277',
    dash: [6, 2],
    routing: go.Routing.Orthogonal,
    curve: go.Curve.None,
    corner: 2,
    fromEndSegmentLength: 16,
    toEndSegmentLength: 16,
    fromSpot: 'Right',
    toSpot: 'Left',
  },
  {
    from: 'wan',
    to: 'vpn-ssl',
    label: 'SSL',
    stroke: '#7f5bc0',
    dash: [2, 2],
  },
  {
    from: 'pc-externo',
    to: 'vpn-ssl',
    label: 'Usuario remoto',
    stroke: '#7f5bc0',
    dash: [4, 2],
  },
  {
    from: 'vpn-ssl',
    to: 'sp-srv',
    label: 'VPN -> Servidores SP',
    stroke: '#7f5bc0',
    dash: [4, 2],
  },
  {
    from: 'vpn-ssl',
    to: 'cwb-srv',
    label: 'VPN -> Servidores CWB',
    stroke: '#7f5bc0',
    dash: [4, 2],
  },
] as Array<Record<string, unknown>>;
